#include "revision.h"

#define STRINGME2(X) #X
#define STRINGME(X) STRINGME2(X)

#define VERSION_FULL_STR STRINGME(VERSION_A) "." STRINGME(VERSION_B) "." STRINGME(VERSION_C) "." STRINGME(VERSION_D)

#define VERSION_NUM (VERSION_D+VERSION_C*10000+VERSION_B*1000000+VERSION_A*100000000)

