#define VERSION_A	0
#define VERSION_B	6
#define VERSION_C	1

#ifdef RELEASEVERSION
#include "revision.h"
#else
#define VERSION_D 0
#endif

#define STRINGME2(X) #X
#define STRINGME(X) STRINGME2(X)

#define VERSION_FULL_STR STRINGME(VERSION_A) "." STRINGME(VERSION_B) "." STRINGME(VERSION_C) "." STRINGME(VERSION_D)

#define VERSION_NUM (VERSION_D+VERSION_C*10000+VERSION_B*1000000+VERSION_A*100000000)

